### ISSUE TITLE
GUI/CLI: Add conspicuous indicator identifying the connected prosEO instance

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#164]
In a multi-mission environment it is difficult (GUI) or impossible (CLI) to know to which prosEO instance the user interface is connected. (In the GUI this can be concluded from the URL in the browser address field, in the CLI there is no indicator whatsoever.)

A prosEO instance identifier shall be added to the data model, and it shall be shown in a conspicuous place in the GUI and in the prompt of the CLI.

**Comment by emelchinger** [comment]
New settngs in application.yml:
```
proseo.instance:
        # instance identifier
        id: local
        # instance environment is one of dev (development), val (evaluation) or ops (operational)
        environment: dev
        # instance environment color for environment setting (background color of left-top and footer), see https://en.wikipedia.org/wiki/Web_colors
        # ops - rgb(0,0,0,.25) - standard
        # dev - BurlyWood
        # val - SkyBlue
        environmentColor: BurlyWood
```
In CLI the prompt is now:
prosEO \<environment\> (\<mission\>@\<identifier\>)\> e.g. `prosEO dev (PTM@local)>`

In GUI the environment is show left top and the identifier top center in the current path. Additional the background color of left top and footer can be defined as environmentColor.
