### ISSUE TITLE
Remove "propagateSlicing" parameter from data model

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#56]
Having propagateSlicing == false leads to massive difficulties in production planning. It was therefore decided to remove the parameter again and to delegate the job of planning orders for different time slices back to the user.

**Comment by tangobravo62** [comment]
Attribute propagateSlicing remove, build OK. In existing databases, column must be dropped manually with `alter table processing_order drop column propagate_slicing`.

"order show" returns processing order without the attribute:
```
prosEO> order show
---
- id: 79
  version: 1
  missionCode: "PTM"
  identifier: "L3_products_9:30-17:30"
  uuid: "3879f149-4aa2-4e50-8836-e910a255f9ce"
  orderState: "INITIAL"
  executionTime: null
  startTime: "2019-11-04T09:30:00"
  stopTime: "2019-11-04T17:00:00"
  slicingType: "TIME_SLICE"
  sliceDuration: 14400
  sliceOverlap: 0
  filterConditions:
  - key: "fileClass"
    parameterType: "STRING"
    parameterValue: "TEST"
  - key: "revision"
    parameterType: "INTEGER"
    parameterValue: "99"
  outputParameters:
  - key: "copernicusCollection"
    parameterType: "INTEGER"
    parameterValue: "77"
  - key: "revision"
    parameterType: "INTEGER"
    parameterValue: "99"
  configuredProcessors:
  - "PTML3_0.1.0_OPER_2020-03-25"
  orbits: []
  requestedProductClasses:
  - "PTM_L3"
  inputProductClasses:
  - "PTM_L2A"
  - "PTM_L2B"
  outputFileClass: "TEST"
  processingMode: "OPER"
```
