### ISSUE TITLE
Configuration update only inserts one static input file

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#71]
Performing `configuration update --file=xxx` with the attached file only creates one static input file:
```
prosEO (S2)> configuration show Sen2Cor
---
- id: 144
  version: 2
  missionCode: "S2"
  processorName: "Sen2Cor"
  configurationVersion: "TEST_2020-06-03_DS"
  dynProcParameters:
  - key: "logging.dumplog"
    parameterType: "STRING"
    parameterValue: "null"
  - key: "Threads"
    parameterType: "INTEGER"
    parameterValue: "16"
  - key: "Processing_Mode"
    parameterType: "STRING"
    parameterValue: "generate_datastrip"
  - key: "logging.root"
    parameterType: "STRING"
    parameterValue: "notice"
  productQuality: "TEST"
  configurationFiles: []
  staticInputFiles:
  - id: 246
    version: 1
    fileType: "GIP_JP2KPA"
    fileNameType: "Physical"
    fileNames:
    - "/proseo/data/196/S2B_OPER_GIP_JP2KPA_MPC__20160222T110000_V20150622T000000_21000101T000000_B00.DBL"
  configuredProcessors:
  - "Sen2Cor_02.08.00_TEST_2020-06-03_DS"
  dockerRunParameters: []
```

[S2_Sen2Cor_conf_TEST_2020-06-03_DS.json.zip](https://github.com/dlr-eoc/prosEO/files/4805188/S2_Sen2Cor_conf_TEST_2020-06-03_DS.json.zip)

**Comment by tangobravo62** [comment]
Corrected:
```
prosEO (S2)> configuration update --file=testfiles/S2_Sen2Cor_conf_TEST_2020-06-03_DS.json
(I2992) Configuration with database ID 144 updated (new version 4)
prosEO (S2)> configuration show Sen2Cor "TEST_2020-06-03_DS"
---
- id: 144
  version: 4
  missionCode: "S2"
  processorName: "Sen2Cor"
  configurationVersion: "TEST_2020-06-03_DS"
  dynProcParameters:
  - key: "logging.dumplog"
    parameterType: "STRING"
    parameterValue: "null"
  - key: "Threads"
    parameterType: "INTEGER"
    parameterValue: "16"
  - key: "Processing_Mode"
    parameterType: "STRING"
    parameterValue: "generate_datastrip"
  - key: "logging.root"
    parameterType: "STRING"
    parameterValue: "notice"
  productQuality: "TEST"
  configurationFiles: []
  staticInputFiles:
  - id: 248
    version: 1
    fileType: "DEM"
    fileNameType: "Directory"
    fileNames:
    - "AUX_DATA/DEM"
  - id: 249
    version: 1
    fileType: "GIP_L2ACFG"
    fileNameType: "Physical"
    fileNames:
    - "/proseo/data/202/S2__OPER_GIP_L2ACFG_MPC__20190805T000005_V20150622T000000_21000101T000000_B00.DBL"
  - id: 250
    version: 1
    fileType: "GIP_JP2KPA"
    fileNameType: "Physical"
    fileNames:
    - "/proseo/data/196/S2B_OPER_GIP_JP2KPA_MPC__20160222T110000_V20150622T000000_21000101T000000_B00.DBL"
  - id: 251
    version: 1
    fileType: "GIP_PROBA2"
    fileNameType: "Physical"
    fileNames:
    - "/proseo/data/206/S2__OPER_GIP_PROBA2_MPC__20200221T000214_V20200225T013000_21000101T000000_B00.xml"
  - id: 252
    version: 1
    fileType: "GIP_L2ACSC"
    fileNameType: "Physical"
    fileNames:
    - "/proseo/data/204/S2__OPER_GIP_L2ACSC_MPC__20181003T000002_V20181007T234500_21000101T000000_B00.DBL"
  - id: 253
    version: 1
    fileType: "GIP_L2ACAC"
    fileNameType: "Physical"
    fileNames:
    - "/proseo/data/200/S2__OPER_GIP_L2ACAC_MPC__20191018T000003_V20150622T000000_21000101T000000_B00.DBL"
  - id: 254
    version: 1
    fileType: "GIP_OLQCPA"
    fileNameType: "Physical"
    fileNames:
    - "/proseo/data/198/S2B_OPER_GIP_OLQCPA_MPC__20191004T000021_V20191021T003000_21000101T000000_B00.zip"
  configuredProcessors:
  - "Sen2Cor_02.08.00_TEST_2020-06-03_DS"
  dockerRunParameters: []
```
